version: "3.9"

services:
  elasticsearch-node1:
    container_name: elasticsearch-node-1
    environment:
      cluster.initial_master_nodes: "node-1,node-2"
      cluster.name: "quiz-regbot_logs"
      discovery.seed_hosts: "elasticsearch-node-1,elasticsearch-node-2"
      node.name: "node-1"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    env_file:
      - path: .env
        required: false
    image: ${ELASTICSEARCH_IMAGE}
    networks:
      - network
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-node-1-data:/usr/share/elasticsearch/data

  elasticsearch-node2:
    container_name: elasticsearch-node-2
    environment:
      cluster.initial_master_nodes: "node-1,node-2"
      cluster.name: "quiz-regbot_logs"
      discovery.seed_hosts: "elasticsearch-node-1,elasticsearch-node-2"
      node.name: "node-2"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    env_file:
      - path: .env
        required: false
    image: ${ELASTICSEARCH_IMAGE}
    networks:
      - network
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - elasticsearch-node-2-data:/usr/share/elasticsearch/data

  kibana:
    command: kibana -e "http://elasticsearch-node-1:9200,http://elasticsearch-node-2:9200"
    container_name: kibana
    image: ${KIBANA_IMAGE}
    networks:
      - network
    ports:
      - 5601:5601

  mysql:
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "TOP_SECRET"
    image: ${MYSQL_IMAGE}
    networks:
      - network
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  network:
    driver: bridge

volumes:
  elasticsearch-node-1-data:
    name: "quiz-regbot_elasticsearch-node-1-data"
  elasticsearch-node-2-data:
    name: "quiz-regbot_elasticsearch-node-2-data"
  mysql-data:
    name: "quiz-regbot_mysqld-data"
